student_attendance/urls.py
from django.contrib import admin  
from django.urls import path  
from attendance import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('add', views.add),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.destroy),
]
# </int:id></int:id></int:id>

attendance/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=100)
    year = models.CharField(max_length=10)
    course = models.CharField(max_length=100)
    email = models.EmailField()
    contact = models.CharField(max_length=15)
    date = models.CharField(max_length=100)

    class Meta:
        db_table = "student"

attendance/forms.py
from django import forms
from .models import Student

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['name', 'year', 'course', 'email', 'contact', 'date']
        widgets = { 'name': forms.TextInput(attrs={ 'class': 'form-control' }),
            'year': forms.TextInput(attrs={ 'class': 'form-control' }),
            'course': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'contact': forms.TextInput(attrs={'class': 'form-control'}),
            'date': forms.TextInput(attrs={'class': 'form-control'}),

    }

attendance/views.py
from django.shortcuts import render, redirect
from .forms import StudentForm
from .models import Student

# Create your views here.

def index(request):
    students = Student.objects.all()
    return render(request,"show.html",{'students':students})

def add(request):
    if request.method == "POST":
        form = StudentForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/')
            except:
                pass
    else:
        form = StudentForm()
    return render(request,'index.html',{'form':form})

def edit(request, id):
    student = Student.objects.get(id=id)
    return render(request,'edit.html', {'student':student})

def update(request, id):
    student = Student.objects.get(id=id)
    form = StudentForm(request.POST, instance = student)
    if form.is_valid():
        form.save()
        return redirect("/")
    return render(request, 'edit.html', {'student': student})

def destroy(request, id):
    student = Student.objects.get(id=id)
    student.delete()
    return redirect("/")

attendance/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{% block title %}{% endblock %}</title>
{% load static %}
<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<!--<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">-->
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>

<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand">
        <img alt="Brand" src="{% static 'attendance/jmc.PNG' %}" width="50" height="50" class="text-top">
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'index' %}">Home</a></li>
        <li><a href="http://127.0.0.1:8000/admin/">Admin</a></li>
        <li><a href="https://github.com/Perzival18" target="_blank">My Github</a></li>
        <li><a href="https://github.com/Perzival18" target="_blank">My PythonAnywhere</a></li>
        <li><a href="https://www.facebook.com/joryyy18/" target="_blank">Contact Me</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<!--  NAVBAR-->
<!--<nav class="navbar navbar-expand-lg navbar-black bg-light" role="navigation">-->
<!--  <div class="container-fluid">-->
<!--    <a class="navbar-brand" href="{% url 'index' %}">-->
<!--        <img src="{% static 'attendance/envelope.PNG' %}" width="50" height="30" alt="envelope's logo" class="d-inline-block align-top">-->
<!--        <span> STUDENTS ATTENDANCE </span>-->
<!--        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">-->
<!--      <span class="navbar-toggler-icon"></span>-->
<!--    </button>-->
<!--    </a>-->
<!--       <ul class="nav">-->
<!--          <li class="nav-item">-->
<!--            <a class="nav-link active" aria-current="page" href="{% url 'index' %}"> Home </a>-->
<!--           </li>-->
<!--          <li class="nav-item">-->
<!--            <a class="nav-link" href="http://127.0.0.1:8000/admin/"> Admin </a>-->
<!--          </li>-->
<!--       </ul>-->
<!--  </div>-->
<!--</nav>-->


<div class="container">
 <div class="row">
    {% block content %}{% endblock %}
 </div>
</div>

<script>
$(document).ready(function() {
    $('#bootstrapdatatable').DataTable({
      "aLengthMenu": [[3, 10, 20, -1], [3, 5, 10, 20, "All"]],
        "iDisplayLength": 5
       }
    );
} );
</script>
</body>
</html>

attendance/templates/edit.html
{% extends "base.html" %}
 
{% block title %}Add New Student Record{% endblock title %}
 
{% block content %}

<div class="col-md-12">
    <form method="POST" class="post-form" action="/update/{{student.id}}">
            {% csrf_token %}
        <div class="container">
    <br>
        <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
        <h3 style="text-align:center;color: red">Update Details</h3>
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Student Id:</label>
        <div class="col-sm-4">
            <input type="text" class="form-control" name="id" id="id_id" required maxlength="20" value="{{ student.id }}"/>
        </div>
      </div>

       <div class="form-group row">
        <label class="col-sm-2 col-form-label">Student Name:</label>
        <div class="col-sm-4">
            <input type="text" class="form-control" name="name" id="id_name" required maxlength="100" value="{{ student.name }}" />
        </div>
      </div>

       <div class="form-group row">
        <label class="col-sm-2 col-form-label">Student Year:</label>
        <div class="col-sm-4">
            <input type="text" class="form-control" name="year" id="id_year" required maxlength="10" value="{{ student.year }}"/>
       </div>
      </div>

       <div class="form-group row">
        <label class="col-sm-2 col-form-label">Student Course:</label>
        <div class="col-sm-4">
            <input type="text" class="form-control" name="course" id="id_course" required maxlength="100" value="{{ student.course }}"/>
        </div>
       </div>

       <div class="form-group row">
        <label class="col-sm-2 col-form-label">Student Email:</label>
        <div class="col-sm-4">
            <input type="email" class="form-control" name="email" id="id_email" required maxlength="254" value="{{ student.email }}" />
        </div>
       </div>

       <div class="form-group row">
        <label class="col-sm-2 col-form-label">Student Contact:</label>
        <div class="col-sm-4">
            <input type="text" class="form-control" name="contact" id="id_contact" required maxlength="15" value="{{ student.contact }}" />
        </div>
       </div>

       <div class="form-group row">
        <label class="col-sm-2 col-form-label">Date & Time:</label>
        <div class="col-sm-4">
            <input type="text" class="form-control" name="date" id="id_date" required maxlength="100" value="{{ student.date }}"/>
        </div>
       </div>

       <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <button type="submit" class="btn btn-success btn-lg">Update</button>
        </div>
       </div>
  </div>

 </form>

</div>
{% endblock content %}   

attendance/templates/index.html
{% extends "base.html" %}
 
{% block title %}Add New Student Records{% endblock title %}
 
{% block content %}
<div class="col-md-12">
         
    <form method="POST" class="post-form" action="/add">
            {% csrf_token %}
        <div class="container">
    <br>
        <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
        <h3 style="text-align:center;color: red">Enter Details</h3>
        </div>
       </div>

       <div class="form-group row">
        <label class="col-sm-2 col-form-label">Student Name:</label>
        <div class="col-sm-4">
          {{ form.name }}
        </div>
       </div>

       <div class="form-group row">
        <label class="col-sm-2 col-form-label">Student Year:</label>
        <div class="col-sm-4">
          {{ form.year }}
        </div>
       </div>

       <div class="form-group row">
        <label class="col-sm-2 col-form-label">Student Course:</label>
        <div class="col-sm-4">
          {{ form.course }}
        </div>
       </div>

       <div class="form-group row">
        <label class="col-sm-2 col-form-label">Student Email:</label>
        <div class="col-sm-4">
          {{ form.email }}
        </div>
       </div>

       <div class="form-group row">
        <label class="col-sm-2 col-form-label">Student Contact:</label>
        <div class="col-sm-4">
          {{ form.contact }}
        </div>
       </div>

       <div class="form-group row">
        <label class="col-sm-2 col-form-label">Date & Time:</label>
        <div class="col-sm-4">
          {{ form.date }}
        </div>
       </div>

       <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <button type="submit" class="btn btn-primary">Submit</button>
        </div>
       </div>
        </div>
    </form>
</div> 
{% endblock content %} 

attendance/templates/show.html
{% extends "base.html" %}

{% block title %}Student Records{% endblock title %}

{% block content %}

 <div class="col-md-12">
        <h4 style="text-align:center;color: red"> STUDENT ATTENDANCE</h4>
     <br>
     <br>
     <span><a href="/add" class="btn btn-primary">Add New Record</a></span>
     <br>
     <br>
        <div class="table-responsive">
  <table id="bootstrapdatatable" class="table table-striped table-bordered" width="100%">
            <thead>
                <th><input type="checkbox" id="checkall" /></th>
                <th> Student ID</th>
                <th> Student Name</th>
                <th> Student Year</th>
                <th> Student Course</th>
                <th> Student Email</th>
                <th> Student Contact</th>
                <th> Date & Time</th>
                <th>Edit</th>
                <th>Delete</th>
             </thead>
            <tbody>
            {% for student in students %}
                <tr>
                 <td><input type="checkbox" class="checkthis" /></td>
                 <td>{{ student.id }}</td>
                 <td>{{ student.name }}</td>
                 <td>{{ student.year }}</td>
                 <td>{{ student.course }}</td>
                 <td>{{ student.email }}</td>
                 <td>{{ student.contact }}</td>
                 <td>{{ student.date }}</td>
                 <td><p data-placement="top" data-toggle="tooltip" title="Edit"><a href="/edit/{{ student.id }}" class="btn btn-primary btn-xs" data-title="Edit" data-toggle="modal" data-target="#edit" ><span class="glyphicon glyphicon-pencil"></span></a></p></td>
                 <td><p data-placement="top" data-toggle="tooltip" title="Delete"><a href="/delete/{{ student.id }}" class="btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete" ><span class="glyphicon glyphicon-trash"></span></a></p></td>
                </tr>
   {% endfor %} 
   </tbody>

  </table>
        </div>
    </div>
{% endblock content %}